global:
  # Target取得の頻度
  scrape_interval:     10s
  evaluation_interval: 10s

scrape_configs:
  # Spring Boot App監視
  - job_name: 'springboot'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['web:8080']
        labels:
          group: 'docker-springboot'

  - job_name: 'docker-host'
    static_configs:
      - targets: ['node-exporter:9100']
        labels:
          group: 'docker-host'